# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1359, 857)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_pt = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_pt.setGeometry(QtCore.QRect(60, 40, 141, 81))
        self.pushButton_pt.setObjectName("pushButton_pt")
        self.pushButton_init = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_init.setGeometry(QtCore.QRect(250, 40, 141, 81))
        self.pushButton_init.setObjectName("pushButton_init")
        self.pushButton_openimg = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_openimg.setGeometry(QtCore.QRect(430, 40, 141, 81))
        self.pushButton_openimg.setObjectName("pushButton_openimg")
        self.pushButton_video = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_video.setGeometry(QtCore.QRect(600, 40, 141, 81))
        self.pushButton_video.setObjectName("pushButton_video")
        self.pushButton_sht = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_sht.setGeometry(QtCore.QRect(770, 40, 141, 81))
        self.pushButton_sht.setObjectName("pushButton_sht")
        self.pushButton_stop = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_stop.setGeometry(QtCore.QRect(940, 40, 141, 81))
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.pushButton_exit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(1110, 40, 141, 81))
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 150, 901, 671))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1000, 150, 311, 651))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1359, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_pt.setText(_translate("MainWindow", "选择模型"))
        self.pushButton_init.setText(_translate("MainWindow", "模型初始化"))
        self.pushButton_openimg.setText(_translate("MainWindow", "打开图片"))
        self.pushButton_video.setText(_translate("MainWindow", "打开视频"))
        self.pushButton_sht.setText(_translate("MainWindow", "摄像头检测"))
        self.pushButton_stop.setText(_translate("MainWindow", "暂停"))
        self.pushButton_exit.setText(_translate("MainWindow", "结束"))
        self.label.setText(_translate("MainWindow", ""))
        self.label_2.setText(_translate("MainWindow", ""))
